/**
 * Generated by scripts/equipment-models.ts — do not edit. The technical equipment in
 * public/models/equipment, one model per catalogue product (`kind` is the product's
 * model3dKind), in metres with the front along +z:
 *
 *   - 'wall'    stands on y = 0 (its bottom edge), centred on x, its back on z = 0;
 *   - 'fitting' is centred on x and y, its back on z = 0 (the sockets of /models/fixtures);
 *   - 'floor'   is centred on x and z with its top at y = 0, everything else below.
 *
 * Sizes are measured from the files. The models are other people's work under CC0, CC BY or
 * CC BY-SA: `author`, `license` and `sourceUrl` are the credit the licence asks for.
 */

import type { StyleId } from '@/lib/design/types';

export type EquipmentFrame = 'wall' | 'fitting' | 'floor';

export interface EquipmentModel {
  slug: string;
  kind: string;
  frame: EquipmentFrame;
  url: string;
  widthCm: number;
  heightCm: number;
  depthCm: number;
  styles: StyleId[];
  title: string;
  source: 'polyhaven' | 'polypizza' | 'sketchfab';
  sourceUrl: string;
  author: string;
  license: string;
}

export const EQUIPMENT_MODELS: EquipmentModel[] = [
  {
    "slug": "panel-12",
    "kind": "electrical_panel",
    "frame": "wall",
    "url": "/models/equipment/panel-12.glb",
    "widthCm": 27.4,
    "heightCm": 33,
    "depthCm": 8.4,
    "styles": [
      "modern",
      "scandinavian",
      "industrial",
      "vintage"
    ],
    "title": "Electrical panel (consumer unit), surface-mounted, door closed",
    "source": "sketchfab",
    "sourceUrl": "https://sketchfab.com/3d-models/f9bd67c84bc84e959b57bd69511f7883",
    "author": "lightjavacode",
    "license": "CC-BY 4.0"
  },
  {
    "slug": "panel-24",
    "kind": "electrical_panel",
    "frame": "wall",
    "url": "/models/equipment/panel-24.glb",
    "widthCm": 30.8,
    "heightCm": 45,
    "depthCm": 8.5,
    "styles": [
      "modern",
      "scandinavian",
      "industrial",
      "vintage"
    ],
    "title": "Electrical panel (distribution board), metal, open, three rows of breakers",
    "source": "polyhaven",
    "sourceUrl": "https://polyhaven.com/a/power_box_01",
    "author": "Poly Haven",
    "license": "CC0"
  },
  {
    "slug": "boiler-combi-24",
    "kind": "boiler",
    "frame": "wall",
    "url": "/models/equipment/boiler-combi-24.glb",
    "widthCm": 41.9,
    "heightCm": 70,
    "depthCm": 35.7,
    "styles": [
      "modern",
      "scandinavian",
      "industrial",
      "vintage"
    ],
    "title": "Wall-hung gas combi boiler",
    "source": "sketchfab",
    "sourceUrl": "https://sketchfab.com/3d-models/2ff78c598c654e36959ed8d3a2c39a43",
    "author": "1-3D.com",
    "license": "CC-BY-SA 4.0"
  },
  {
    "slug": "water-heater-80",
    "kind": "boiler",
    "frame": "wall",
    "url": "/models/equipment/water-heater-80.glb",
    "widthCm": 47.7,
    "heightCm": 80,
    "depthCm": 51.5,
    "styles": [
      "modern",
      "scandinavian",
      "industrial",
      "vintage"
    ],
    "title": "Electric water heater (storage), 80 L, vertical",
    "source": "sketchfab",
    "sourceUrl": "https://sketchfab.com/3d-models/2a1edaa43d61499a905f034640e2877a",
    "author": "rk_m",
    "license": "CC-BY 4.0"
  },
  {
    "slug": "ac-9000",
    "kind": "ac_unit",
    "frame": "wall",
    "url": "/models/equipment/ac-9000.glb",
    "widthCm": 80,
    "heightCm": 28.1,
    "depthCm": 18.9,
    "styles": [
      "modern",
      "scandinavian",
      "industrial",
      "vintage"
    ],
    "title": "Wall split air conditioner, indoor unit (9,000 BTU)",
    "source": "sketchfab",
    "sourceUrl": "https://sketchfab.com/3d-models/d3a156127b2c478dabc40e3a9597df82",
    "author": "rk_m",
    "license": "CC-BY 4.0"
  },
  {
    "slug": "ac-12000",
    "kind": "ac_unit",
    "frame": "wall",
    "url": "/models/equipment/ac-12000.glb",
    "widthCm": 88,
    "heightCm": 31.5,
    "depthCm": 21.5,
    "styles": [
      "modern",
      "scandinavian",
      "industrial",
      "vintage"
    ],
    "title": "Wall split air conditioner, indoor unit (12,000 BTU)",
    "source": "sketchfab",
    "sourceUrl": "https://sketchfab.com/3d-models/da8f719b60e9406fb16c84a0bf404297",
    "author": "rk_m",
    "license": "CC-BY 4.0"
  },
  {
    "slug": "hood-chimney-60",
    "kind": "cooker_hood",
    "frame": "wall",
    "url": "/models/equipment/hood-chimney-60.glb",
    "widthCm": 60,
    "heightCm": 60,
    "depthCm": 39.7,
    "styles": [
      "modern",
      "scandinavian",
      "industrial",
      "vintage"
    ],
    "title": "Chimney cooker hood, 60 cm, stainless steel",
    "source": "sketchfab",
    "sourceUrl": "https://sketchfab.com/3d-models/e846cb48e88446808af55976ff76b1da",
    "author": "govindu94",
    "license": "CC-BY 4.0"
  },
  {
    "slug": "hood-flat-60",
    "kind": "cooker_hood",
    "frame": "wall",
    "url": "/models/equipment/hood-flat-60.glb",
    "widthCm": 60,
    "heightCm": 21.9,
    "depthCm": 26.4,
    "styles": [
      "modern",
      "scandinavian",
      "industrial",
      "vintage"
    ],
    "title": "Built-in cooker hood, 60 cm, glass front",
    "source": "sketchfab",
    "sourceUrl": "https://sketchfab.com/3d-models/0be84630c8e84508926c5922c541e1ce",
    "author": "GLOBALO",
    "license": "CC-BY 4.0"
  },
  {
    "slug": "fan-100",
    "kind": "bathroom_fan",
    "frame": "wall",
    "url": "/models/equipment/fan-100.glb",
    "widthCm": 15,
    "heightCm": 15,
    "depthCm": 1.2,
    "styles": [
      "modern",
      "scandinavian",
      "industrial",
      "vintage"
    ],
    "title": "Bathroom extractor fan, louvred front",
    "source": "polypizza",
    "sourceUrl": "https://poly.pizza/m/PCqBwDkgAz",
    "author": "J-Toastie",
    "license": "CC-BY 3.0"
  },
  {
    "slug": "drain-15",
    "kind": "floor_drain",
    "frame": "floor",
    "url": "/models/equipment/drain-15.glb",
    "widthCm": 15,
    "heightCm": 0.3,
    "depthCm": 15,
    "styles": [
      "modern",
      "scandinavian",
      "industrial",
      "vintage"
    ],
    "title": "Floor drain grate, square, stainless steel",
    "source": "sketchfab",
    "sourceUrl": "https://sketchfab.com/3d-models/d3cb922e9304417bad755b8c7298ff4f",
    "author": "Jesus Fernandez Garcia",
    "license": "CC-BY 4.0"
  },
  {
    "slug": "socket-tv",
    "kind": "socket_tv",
    "frame": "fitting",
    "url": "/models/equipment/socket-tv.glb",
    "widthCm": 8,
    "heightCm": 8,
    "depthCm": 0.6,
    "styles": [
      "modern",
      "scandinavian",
      "industrial",
      "vintage"
    ],
    "title": "TV socket (coaxial), wall plate, black",
    "source": "sketchfab",
    "sourceUrl": "https://sketchfab.com/3d-models/6c7bd622341945baa49161751b8c6d1e",
    "author": "deslancer",
    "license": "CC-BY 4.0"
  },
  {
    "slug": "socket-data",
    "kind": "socket_data",
    "frame": "fitting",
    "url": "/models/equipment/socket-data.glb",
    "widthCm": 8,
    "heightCm": 8,
    "depthCm": 0.6,
    "styles": [
      "modern",
      "scandinavian",
      "industrial",
      "vintage"
    ],
    "title": "Data socket (RJ45), wall plate, white",
    "source": "sketchfab",
    "sourceUrl": "https://sketchfab.com/3d-models/ded403c85dee45b7ad8a6bcc8c3b2754",
    "author": "1-3D.com",
    "license": "CC-BY-SA 4.0"
  }
];
