/**
 * Generated by scripts/fixture-models.ts — do not edit. The electrical layer's 3D fixtures
 * (public/models/fixtures), one entry per model with the kinds it stands for.
 */

import type { ElectricalKind } from '@/lib/design/types';

export interface FixtureModel {
  slug: string;
  kinds: ElectricalKind[];
  mount: 'wall' | 'ceiling';
  url: string;
  widthCm: number;
  heightCm: number;
  depthCm: number;
  license: string;
  author: string;
}

export const FIXTURE_MODELS: FixtureModel[] = [
  {
    "slug": "socket-eu",
    "kinds": [
      "socket",
      "socket_double",
      "socket_high",
      "socket_kitchen",
      "internet",
      "tv"
    ],
    "mount": "wall",
    "url": "/models/fixtures/socket-eu.glb",
    "widthCm": 8,
    "heightCm": 8,
    "depthCm": 2,
    "license": "CC-BY 3.0",
    "author": "J-Toastie"
  },
  {
    "slug": "switch",
    "kinds": [
      "switch"
    ],
    "mount": "wall",
    "url": "/models/fixtures/switch.glb",
    "widthCm": 8,
    "heightCm": 8,
    "depthCm": 1,
    "license": "CC-BY 3.0",
    "author": "Poly by Google"
  },
  {
    "slug": "wall-lamp",
    "kinds": [
      "light_wall"
    ],
    "mount": "wall",
    "url": "/models/fixtures/wall-lamp.glb",
    "widthCm": 27,
    "heightCm": 43,
    "depthCm": 14,
    "license": "CC0",
    "author": "Poly Haven"
  },
  {
    "slug": "bulb",
    "kinds": [
      "light_ceiling"
    ],
    "mount": "ceiling",
    "url": "/models/fixtures/bulb.glb",
    "widthCm": 6,
    "heightCm": 10,
    "depthCm": 6,
    "license": "CC0",
    "author": "Poly Haven"
  }
];
