/**
 * Generated by scripts/fixture-models.ts — do not edit. The 3D fixtures in public/models/fixtures:
 * the electrical layer's sockets, switches and lamps (one entry per model with the kinds it
 * stands for) and the doors and windows (kinds empty; `parts` names the nodes a door has).
 */

import type { ElectricalKind } from '@/lib/design/types';

export interface FixtureModel {
  slug: string;
  kinds: ElectricalKind[];
  mount: 'wall' | 'ceiling' | 'door' | 'window';
  url: string;
  widthCm: number;
  heightCm: number;
  depthCm: number;
  parts?: Array<'frame' | 'leaf' | 'body'>;
  /** What the studio draws this for when nothing is chosen: a door or window without a product, the casing of a bare leaf and of an archway, the rose under a catalogue lamp. */
  role?: 'door' | 'window' | 'casing' | 'rose';
  license: string;
  author: string;
}

export const FIXTURE_MODELS: FixtureModel[] = [
  {
    "slug": "socket-eu",
    "kinds": [
      "socket",
      "socket_double",
      "socket_high",
      "socket_kitchen",
      "internet",
      "tv"
    ],
    "mount": "wall",
    "url": "/models/fixtures/socket-eu.glb",
    "widthCm": 8,
    "heightCm": 8,
    "depthCm": 2,
    "license": "CC-BY 3.0",
    "author": "J-Toastie"
  },
  {
    "slug": "socket-twin",
    "kinds": [
      "socket",
      "socket_double",
      "socket_high",
      "socket_kitchen",
      "internet",
      "tv"
    ],
    "mount": "wall",
    "url": "/models/fixtures/socket-twin.glb",
    "widthCm": 8,
    "heightCm": 5,
    "depthCm": 1,
    "license": "CC-BY 3.0",
    "author": "J-Toastie"
  },
  {
    "slug": "switch",
    "kinds": [
      "switch"
    ],
    "mount": "wall",
    "url": "/models/fixtures/switch.glb",
    "widthCm": 8,
    "heightCm": 8,
    "depthCm": 1,
    "license": "CC-BY 3.0",
    "author": "Poly by Google"
  },
  {
    "slug": "switch-classic",
    "kinds": [
      "switch"
    ],
    "mount": "wall",
    "url": "/models/fixtures/switch-classic.glb",
    "widthCm": 5,
    "heightCm": 8,
    "depthCm": 2,
    "license": "CC-BY 3.0",
    "author": "jeremy"
  },
  {
    "slug": "wall-lamp",
    "kinds": [
      "light_wall"
    ],
    "mount": "wall",
    "url": "/models/fixtures/wall-lamp.glb",
    "widthCm": 27,
    "heightCm": 43,
    "depthCm": 14,
    "license": "CC0",
    "author": "Poly Haven"
  },
  {
    "slug": "wall-sconce",
    "kinds": [
      "light_wall"
    ],
    "mount": "wall",
    "url": "/models/fixtures/wall-sconce.glb",
    "widthCm": 15,
    "heightCm": 34,
    "depthCm": 25,
    "license": "CC0",
    "author": "Poly Haven"
  },
  {
    "slug": "wall-lamp-brass",
    "kinds": [
      "light_wall"
    ],
    "mount": "wall",
    "url": "/models/fixtures/wall-lamp-brass.glb",
    "widthCm": 19,
    "heightCm": 40,
    "depthCm": 32,
    "license": "CC-BY 3.0",
    "author": "jrich01"
  },
  {
    "slug": "bulb",
    "kinds": [
      "light_ceiling"
    ],
    "mount": "ceiling",
    "url": "/models/fixtures/bulb.glb",
    "widthCm": 8,
    "heightCm": 40,
    "depthCm": 8,
    "license": "CC0",
    "author": "reelpersen"
  },
  {
    "slug": "ceiling-globe",
    "kinds": [
      "light_ceiling"
    ],
    "mount": "ceiling",
    "url": "/models/fixtures/ceiling-globe.glb",
    "widthCm": 43,
    "heightCm": 95,
    "depthCm": 43,
    "license": "CC0",
    "author": "Poly Haven"
  },
  {
    "slug": "ceiling-pendant",
    "kinds": [
      "light_ceiling"
    ],
    "mount": "ceiling",
    "url": "/models/fixtures/ceiling-pendant.glb",
    "widthCm": 36,
    "heightCm": 101,
    "depthCm": 36,
    "license": "CC0",
    "author": "Quaternius"
  },
  {
    "slug": "ceiling-disc",
    "kinds": [
      "light_ceiling"
    ],
    "mount": "ceiling",
    "url": "/models/fixtures/ceiling-disc.glb",
    "widthCm": 61,
    "heightCm": 32,
    "depthCm": 61,
    "license": "CC-BY 3.0",
    "author": "Zsky"
  },
  {
    "slug": "ceiling-rose",
    "kinds": [],
    "mount": "ceiling",
    "url": "/models/fixtures/ceiling-rose.glb",
    "widthCm": 12,
    "heightCm": 5,
    "depthCm": 12,
    "role": "rose",
    "license": "CC-BY 3.0",
    "author": "Jarlan Perez"
  },
  {
    "slug": "spot-flush",
    "kinds": [
      "light_spot"
    ],
    "mount": "ceiling",
    "url": "/models/fixtures/spot-flush.glb",
    "widthCm": 10,
    "heightCm": 4,
    "depthCm": 10,
    "license": "CC-BY 3.0",
    "author": "Jarlan Perez"
  },
  {
    "slug": "spot-square",
    "kinds": [
      "light_spot"
    ],
    "mount": "ceiling",
    "url": "/models/fixtures/spot-square.glb",
    "widthCm": 10,
    "heightCm": 20,
    "depthCm": 10,
    "license": "CC0",
    "author": "Kenney"
  },
  {
    "slug": "strip-led",
    "kinds": [
      "light_strip"
    ],
    "mount": "wall",
    "url": "/models/fixtures/strip-led.glb",
    "widthCm": 91,
    "heightCm": 4,
    "depthCm": 4,
    "license": "CC0",
    "author": "Poly Haven"
  },
  {
    "slug": "strip-furniture",
    "kinds": [
      "light_furniture"
    ],
    "mount": "wall",
    "url": "/models/fixtures/strip-furniture.glb",
    "widthCm": 91,
    "heightCm": 4,
    "depthCm": 4,
    "license": "CC0",
    "author": "Poly Haven"
  },
  {
    "slug": "door-frame",
    "kinds": [],
    "mount": "door",
    "url": "/models/fixtures/door-frame.glb",
    "widthCm": 96,
    "heightCm": 212,
    "depthCm": 18,
    "parts": [
      "body"
    ],
    "role": "casing",
    "license": "CC0",
    "author": "Kenney"
  },
  {
    "slug": "door-oak",
    "kinds": [],
    "mount": "door",
    "url": "/models/fixtures/door-oak.glb",
    "widthCm": 96,
    "heightCm": 212,
    "depthCm": 20,
    "parts": [
      "frame",
      "leaf"
    ],
    "license": "CC0",
    "author": "Quaternius"
  },
  {
    "slug": "door-nordic",
    "kinds": [],
    "mount": "door",
    "url": "/models/fixtures/door-nordic.glb",
    "widthCm": 96,
    "heightCm": 212,
    "depthCm": 22,
    "parts": [
      "frame",
      "leaf"
    ],
    "license": "CC0",
    "author": "Quaternius"
  },
  {
    "slug": "door-flat",
    "kinds": [],
    "mount": "door",
    "url": "/models/fixtures/door-flat.glb",
    "widthCm": 96,
    "heightCm": 212,
    "depthCm": 22,
    "parts": [
      "frame",
      "leaf"
    ],
    "role": "door",
    "license": "CC0",
    "author": "Quaternius"
  },
  {
    "slug": "door-classic",
    "kinds": [],
    "mount": "door",
    "url": "/models/fixtures/door-classic.glb",
    "widthCm": 96,
    "heightCm": 212,
    "depthCm": 23,
    "parts": [
      "frame",
      "leaf"
    ],
    "license": "CC-BY 3.0",
    "author": "Wesley Thompson"
  },
  {
    "slug": "door-country",
    "kinds": [],
    "mount": "door",
    "url": "/models/fixtures/door-country.glb",
    "widthCm": 86,
    "heightCm": 205,
    "depthCm": 24,
    "parts": [
      "leaf"
    ],
    "license": "CC0",
    "author": "Kenney"
  },
  {
    "slug": "entrance-door-classic",
    "kinds": [],
    "mount": "door",
    "url": "/models/fixtures/entrance-door-classic.glb",
    "widthCm": 100,
    "heightCm": 215,
    "depthCm": 23,
    "parts": [
      "frame",
      "leaf"
    ],
    "license": "CC0",
    "author": "Quaternius"
  },
  {
    "slug": "entrance-door-metal",
    "kinds": [],
    "mount": "door",
    "url": "/models/fixtures/entrance-door-metal.glb",
    "widthCm": 90,
    "heightCm": 210,
    "depthCm": 15,
    "parts": [
      "leaf"
    ],
    "license": "CC0",
    "author": "Quaternius"
  },
  {
    "slug": "entrance-door-red",
    "kinds": [],
    "mount": "door",
    "url": "/models/fixtures/entrance-door-red.glb",
    "widthCm": 86,
    "heightCm": 205,
    "depthCm": 24,
    "parts": [
      "leaf"
    ],
    "license": "CC0",
    "author": "Kenney"
  },
  {
    "slug": "window-nordic",
    "kinds": [],
    "mount": "window",
    "url": "/models/fixtures/window-nordic.glb",
    "widthCm": 90,
    "heightCm": 120,
    "depthCm": 14,
    "parts": [
      "body"
    ],
    "license": "CC0",
    "author": "Quaternius"
  },
  {
    "slug": "window-grid",
    "kinds": [],
    "mount": "window",
    "url": "/models/fixtures/window-grid.glb",
    "widthCm": 180,
    "heightCm": 150,
    "depthCm": 13,
    "parts": [
      "body"
    ],
    "license": "CC0",
    "author": "Quaternius"
  },
  {
    "slug": "window-wood",
    "kinds": [],
    "mount": "window",
    "url": "/models/fixtures/window-wood.glb",
    "widthCm": 100,
    "heightCm": 120,
    "depthCm": 9,
    "parts": [
      "body"
    ],
    "license": "CC-BY 3.0",
    "author": "Justin Randall"
  },
  {
    "slug": "window-square",
    "kinds": [],
    "mount": "window",
    "url": "/models/fixtures/window-square.glb",
    "widthCm": 120,
    "heightCm": 120,
    "depthCm": 9,
    "parts": [
      "body"
    ],
    "license": "CC-BY 3.0",
    "author": "Poly by Google"
  }
];
