/**
 * Generated by scripts/radiator-models.ts — do not edit. The central-heating radiators in
 * public/models/radiators, one SECTION per model: centred on x with an x-extent of exactly
 * `sectionWidthCm` (copies placed at that pitch touch and their collectors join into pipes),
 * standing on y = 0, its back on z = 0 and its front along +z. A radiator is the section
 * repeated; `wattsPerSection` is what the sizing rule divides a room's heat demand by.
 */

import type { StyleId } from '@/lib/design/types';

export interface RadiatorModel {
  slug: string;
  url: string;
  sectionWidthCm: number;
  heightCm: number;
  depthCm: number;
  wattsPerSection: number;
  styles: StyleId[];
}

export const RADIATOR_MODELS: RadiatorModel[] = [
  {
    "slug": "radiator-panel",
    "url": "/models/radiators/radiator-panel.glb",
    "sectionWidthCm": 10,
    "heightCm": 60,
    "depthCm": 10,
    "wattsPerSection": 170,
    "styles": [
      "modern"
    ]
  },
  {
    "slug": "radiator-aluminium",
    "url": "/models/radiators/radiator-aluminium.glb",
    "sectionWidthCm": 8,
    "heightCm": 58,
    "depthCm": 9.5,
    "wattsPerSection": 180,
    "styles": [
      "scandinavian",
      "modern"
    ]
  },
  {
    "slug": "radiator-column",
    "url": "/models/radiators/radiator-column.glb",
    "sectionWidthCm": 6,
    "heightCm": 76,
    "depthCm": 14,
    "wattsPerSection": 120,
    "styles": [
      "industrial"
    ]
  },
  {
    "slug": "radiator-classic",
    "url": "/models/radiators/radiator-classic.glb",
    "sectionWidthCm": 7.6,
    "heightCm": 66,
    "depthCm": 16,
    "wattsPerSection": 110,
    "styles": [
      "vintage"
    ]
  }
];
