/**
 * Generated by scripts/railing-models.ts — do not edit. The balcony railing in
 * public/models/railings: one MODULE, centred on x with an x-extent of exactly `pitchCm`
 * (modules placed at that pitch touch and share their posts), standing on y = 0, centred on z.
 * A railing is as many modules as fit its length, stretched to fill it, and to its height.
 */

export interface RailingModel {
  slug: string;
  url: string;
  pitchCm: number;
  heightCm: number;
  depthCm: number;
}

export const RAILING_MODEL: RailingModel = {
  "slug": "railing",
  "url": "/models/railings/railing.glb",
  "pitchCm": 100,
  "heightCm": 100,
  "depthCm": 5
};
