import type { HomeState, RoomType } from './types';

export const HOME_STATES: Record<
  HomeState,
  { labelKa: string; descriptionKa: string; includedPhases: number[] }
> = {
  black_frame: {
    labelKa: 'შავი კარკასი',
    descriptionKa:
      'მხოლოდ ბეტონის კედლები, სახლი სრულიად ცარიელია. საჭიროა ყველა სამუშაო.',
    includedPhases: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
  },
  white_frame: {
    labelKa: 'თეთრი კარკასი',
    descriptionKa:
      'კედლები დაშტუკატურებულია, იატაკი მოსწორებულია, ელექტრო და წყალი შეყვანილია.',
    includedPhases: [9, 10, 11, 12, 13, 14, 15, 16, 17],
  },
  green_frame: {
    labelKa: 'მწვანე კარკასი',
    descriptionKa: 'სრულად მზა სახლი, საჭიროა მხოლოდ მებელი და ინტერიერი.',
    includedPhases: [17],
  },
};

export const ROOM_TYPES: Record<RoomType, { labelKa: string; defaultHeight: number }> = {
  living_room: { labelKa: 'მისაღები ოთახი', defaultHeight: 2.8 },
  bedroom: { labelKa: 'საძინებელი', defaultHeight: 2.8 },
  kitchen: { labelKa: 'სამზარეულო', defaultHeight: 2.7 },
  bathroom: { labelKa: 'სველი წერტილი', defaultHeight: 2.5 },
  toilet: { labelKa: 'ტუალეტი', defaultHeight: 2.5 },
  hallway: { labelKa: 'დერეფანი', defaultHeight: 2.8 },
  balcony: { labelKa: 'აივანი', defaultHeight: 2.5 },
  storage: { labelKa: 'საწყობი', defaultHeight: 2.5 },
  office: { labelKa: 'საოფისე ოთახი', defaultHeight: 2.8 },
};

export const WET_ROOM_TYPES: RoomType[] = ['bathroom', 'toilet', 'kitchen'];

export const WORKER_RATES = {
  demolition: { labelKa: 'დემონტაჟი', pricePerM2: 8, unit: 'm2' as const },
  plumbing_rough: { labelKa: 'სანტექნიკა (შიდა)', pricePerM2: 25, unit: 'm2' as const },
  electrical_rough: { labelKa: 'ელექტრო (შიდა)', pricePerM2: 20, unit: 'm2' as const },
  insulation: { labelKa: 'იზოლაცია', pricePerM2: 12, unit: 'm2' as const },
  screed: { labelKa: 'სტიაჟკა', pricePerM2: 15, unit: 'm2' as const },
  plastering: { labelKa: 'შტუკატურება', pricePerM2: 18, unit: 'm2' as const },
  waterproofing: { labelKa: 'ჰიდროიზოლაცია', pricePerM2: 10, unit: 'm2' as const },
  tiling: { labelKa: 'კერამიკის დება', pricePerM2: 22, unit: 'm2' as const },
  windows: { labelKa: 'ფანჯრების დაყენება', pricePerUnit: 80, unit: 'unit' as const },
  doors: { labelKa: 'კარების დაყენება', pricePerUnit: 60, unit: 'unit' as const },
  flooring: { labelKa: 'სართულის გაკეთება', pricePerM2: 14, unit: 'm2' as const },
  ceiling: { labelKa: 'ჭერის გაკეთება', pricePerM2: 16, unit: 'm2' as const },
  painting: { labelKa: 'მხატვრობა / შეღებვა', pricePerM2: 8, unit: 'm2' as const },
  electrical_finish: { labelKa: 'ელექტრო (სახე)', pricePerM2: 10, unit: 'm2' as const },
  plumbing_finish: { labelKa: 'სანტექნიკა (სახე)', pricePerM2: 15, unit: 'm2' as const },
} as const;

export type WorkerRateKey = keyof typeof WORKER_RATES;

export interface MaterialRate {
  labelKa: string;
  qtyPerM2: number;
  unit: 'm2' | 'linear_m' | 'piece' | 'liter' | 'kg' | 'm3';
  wasteFactorPct: number;
  phase: number;
  basis: 'floor' | 'wall' | 'ceiling' | 'wet_floor' | 'perimeter';
  linkedCategorySlug?: string | null;
  estimatedPriceGEL?: number | null;
}

export const MATERIAL_RATES_PER_M2: Record<string, MaterialRate> = {
  gas_block: {
    labelKa: 'გაზობეტონი (პარტიციები)',
    qtyPerM2: 0.12,
    unit: 'm3',
    wasteFactorPct: 10,
    phase: 1,
    basis: 'floor',
    estimatedPriceGEL: 320,
  },
  construction_mesh: {
    labelKa: 'არმატურის ბადე',
    qtyPerM2: 0.8,
    unit: 'm2',
    wasteFactorPct: 10,
    phase: 1,
    basis: 'wall',
    estimatedPriceGEL: 6,
  },
  construction_foam: {
    labelKa: 'მშენებლური ქაფი',
    qtyPerM2: 0.05,
    unit: 'piece',
    wasteFactorPct: 0,
    phase: 1,
    basis: 'floor',
    estimatedPriceGEL: 12,
  },
  ppr_pipe_20mm: {
    labelKa: 'PPR მილი 20მმ',
    qtyPerM2: 1.2,
    unit: 'linear_m',
    wasteFactorPct: 10,
    phase: 2,
    basis: 'floor',
    estimatedPriceGEL: 3.5,
  },
  ppr_pipe_25mm: {
    labelKa: 'PPR მილი 25მმ',
    qtyPerM2: 0.5,
    unit: 'linear_m',
    wasteFactorPct: 10,
    phase: 2,
    basis: 'floor',
    estimatedPriceGEL: 4.5,
  },
  sewage_pipe_50mm: {
    labelKa: 'კანალიზაცია 50მმ',
    qtyPerM2: 0.4,
    unit: 'linear_m',
    wasteFactorPct: 10,
    phase: 2,
    basis: 'wet_floor',
    estimatedPriceGEL: 7,
  },
  sewage_pipe_110mm: {
    labelKa: 'კანალიზაცია 110მმ',
    qtyPerM2: 0.15,
    unit: 'linear_m',
    wasteFactorPct: 10,
    phase: 2,
    basis: 'floor',
    estimatedPriceGEL: 15,
  },
  pipe_fittings: {
    labelKa: 'PPR ფიტინგები',
    qtyPerM2: 2,
    unit: 'piece',
    wasteFactorPct: 5,
    phase: 2,
    basis: 'floor',
    estimatedPriceGEL: 2.5,
  },
  cable_1_5mm: {
    labelKa: 'კაბელი 1.5მმ² (განათება)',
    qtyPerM2: 1.5,
    unit: 'linear_m',
    wasteFactorPct: 15,
    phase: 3,
    basis: 'floor',
    estimatedPriceGEL: 1.8,
  },
  cable_2_5mm: {
    labelKa: 'კაბელი 2.5მმ² (როზეტები)',
    qtyPerM2: 2.5,
    unit: 'linear_m',
    wasteFactorPct: 15,
    phase: 3,
    basis: 'floor',
    estimatedPriceGEL: 2.8,
  },
  cable_4mm: {
    labelKa: 'კაბელი 4მმ² (კლიმატი/ღუმელი)',
    qtyPerM2: 0.3,
    unit: 'linear_m',
    wasteFactorPct: 10,
    phase: 3,
    basis: 'floor',
    estimatedPriceGEL: 4.5,
  },
  corrugated_tube: {
    labelKa: 'გოფრი (ელ. კაბელებისთვის)',
    qtyPerM2: 4,
    unit: 'linear_m',
    wasteFactorPct: 10,
    phase: 3,
    basis: 'floor',
    estimatedPriceGEL: 1.2,
  },
  junction_boxes: {
    labelKa: 'სარქველი ყუთები',
    qtyPerM2: 0.3,
    unit: 'piece',
    wasteFactorPct: 0,
    phase: 3,
    basis: 'floor',
    estimatedPriceGEL: 4,
  },
  circuit_breakers: {
    labelKa: 'ავტომატები',
    qtyPerM2: 0.1,
    unit: 'piece',
    wasteFactorPct: 0,
    phase: 3,
    basis: 'floor',
    estimatedPriceGEL: 18,
  },
  eps_insulation: {
    labelKa: 'პენოპლასტი (EPS)',
    qtyPerM2: 1.1,
    unit: 'm2',
    wasteFactorPct: 10,
    phase: 5,
    basis: 'floor',
    estimatedPriceGEL: 11,
  },
  vapor_barrier: {
    labelKa: 'ორთქლგამძლე ფილა',
    qtyPerM2: 1.15,
    unit: 'm2',
    wasteFactorPct: 10,
    phase: 5,
    basis: 'floor',
    estimatedPriceGEL: 3.5,
  },
  cement: {
    labelKa: 'ცემენტი M400',
    qtyPerM2: 12,
    unit: 'kg',
    wasteFactorPct: 5,
    phase: 6,
    basis: 'floor',
    estimatedPriceGEL: 0.65,
  },
  sand: {
    labelKa: 'ქვიშა',
    qtyPerM2: 0.035,
    unit: 'm3',
    wasteFactorPct: 5,
    phase: 6,
    basis: 'floor',
    estimatedPriceGEL: 90,
  },
  self_leveling: {
    labelKa: 'თვითსწორი ნარევი',
    qtyPerM2: 4,
    unit: 'kg',
    wasteFactorPct: 5,
    phase: 6,
    basis: 'floor',
    estimatedPriceGEL: 2.2,
  },
  floor_primer: {
    labelKa: 'გრუნტი (სართულისთვის)',
    qtyPerM2: 0.2,
    unit: 'liter',
    wasteFactorPct: 10,
    phase: 6,
    basis: 'floor',
    estimatedPriceGEL: 8,
  },
  gypsum_plaster: {
    labelKa: 'გიფსის შტუკატური (Knauf)',
    qtyPerM2: 10,
    unit: 'kg',
    wasteFactorPct: 10,
    phase: 7,
    basis: 'wall',
    estimatedPriceGEL: 1.4,
  },
  plaster_primer: {
    labelKa: 'გრუნტი (კედლებისთვის)',
    qtyPerM2: 0.15,
    unit: 'liter',
    wasteFactorPct: 5,
    phase: 7,
    basis: 'wall',
    estimatedPriceGEL: 8,
  },
  corner_beads: {
    labelKa: 'კუთხის პროფილი',
    qtyPerM2: 0.4,
    unit: 'linear_m',
    wasteFactorPct: 5,
    phase: 7,
    basis: 'perimeter',
    estimatedPriceGEL: 3,
  },
  joint_compound: {
    labelKa: 'შპაკლი (ფინიშური)',
    qtyPerM2: 1.2,
    unit: 'kg',
    wasteFactorPct: 10,
    phase: 7,
    basis: 'wall',
    estimatedPriceGEL: 2.5,
  },
  waterproof_membrane: {
    labelKa: 'ჰიდროიზოლაციური მემბრანა',
    qtyPerM2: 1.5,
    unit: 'kg',
    wasteFactorPct: 10,
    phase: 8,
    basis: 'wet_floor',
    estimatedPriceGEL: 9,
  },
  waterproof_tape: {
    labelKa: 'ჰიდრო ლენტი (კუთხეები)',
    qtyPerM2: 1.2,
    unit: 'linear_m',
    wasteFactorPct: 5,
    phase: 8,
    basis: 'wet_floor',
    estimatedPriceGEL: 4,
  },
  silicone: {
    labelKa: 'სილიკონი',
    qtyPerM2: 0.1,
    unit: 'piece',
    wasteFactorPct: 0,
    phase: 8,
    basis: 'wet_floor',
    estimatedPriceGEL: 10,
  },
  tile_adhesive: {
    labelKa: 'კერამიკის წებო',
    qtyPerM2: 5,
    unit: 'kg',
    wasteFactorPct: 10,
    phase: 9,
    basis: 'wet_floor',
    estimatedPriceGEL: 1.2,
  },
  tile_grout: {
    labelKa: 'ფუგა (ნაკერებისთვის)',
    qtyPerM2: 0.5,
    unit: 'kg',
    wasteFactorPct: 5,
    phase: 9,
    basis: 'wet_floor',
    estimatedPriceGEL: 6,
  },
  tile_spacers: {
    labelKa: 'კერამიკის ჯვრები',
    qtyPerM2: 30,
    unit: 'piece',
    wasteFactorPct: 0,
    phase: 9,
    basis: 'wet_floor',
    estimatedPriceGEL: 0.15,
  },
  tile_leveling_svp: {
    labelKa: 'SVP გასწორების სისტემა',
    qtyPerM2: 8,
    unit: 'piece',
    wasteFactorPct: 5,
    phase: 9,
    basis: 'wet_floor',
    estimatedPriceGEL: 0.6,
  },
  wall_primer_paint: {
    labelKa: 'გრუნტი (საღებავამდე)',
    qtyPerM2: 0.12,
    unit: 'liter',
    wasteFactorPct: 5,
    phase: 13,
    basis: 'wall',
    estimatedPriceGEL: 8,
  },
  interior_paint: {
    labelKa: 'ინტერიერის საღებავი',
    qtyPerM2: 0.14,
    unit: 'liter',
    wasteFactorPct: 10,
    phase: 13,
    basis: 'wall',
    estimatedPriceGEL: 14,
    linkedCategorySlug: 'paint',
  },
  ceiling_paint: {
    labelKa: 'ჭერის საღებავი',
    qtyPerM2: 0.12,
    unit: 'liter',
    wasteFactorPct: 10,
    phase: 13,
    basis: 'ceiling',
    estimatedPriceGEL: 13,
  },
};

export const PHASE_NAMES: Record<number, string> = {
  1: 'სტრუქტურა და დემონტაჟი',
  2: 'სანტექნიკა (შიდა)',
  3: 'ელექტრო (შიდა)',
  5: 'იზოლაცია',
  6: 'სართულის სტიაჟკა',
  7: 'შტუკატურება',
  8: 'ჰიდროიზოლაცია',
  9: 'კერამიკა და ფილები',
  10: 'კარები და ფანჯრები',
  11: 'სართული (ფინიშური)',
  12: 'ჭერი',
  13: 'საღებავი',
  14: 'ელექტრო (სახე)',
  15: 'სანტექნიკა (სახე)',
  16: 'სანიტარია და კრანები',
  17: 'მებელი და ინტერიერი',
  18: 'დასუფთავება',
};

export const CONTINGENCY_PCT = 15;
