-- The interior paints the four styles colour their rooms in (`rooms` in lib/design/styles.ts —
-- the bedroom a calmer colour than the living room, the hall in light grey …), so a generated flat's
-- walls are paint that the budget buys rather than bare plaster. `pnpm textures:stock` writes the
-- same products (the `paint(…)` entries in scripts/stock-textures.ts) with their textures, which
-- ship in public/textures (paint-<name>-diffuse.webp, the plaster acg-Plaster002 coloured to each)
-- and their pictures in public/uploads/products. Idempotent: a slug that exists is left alone, and
-- a database without the paint category gets nothing (the seeds make it, and the script the paints).
-- No JSON cast: the JSON columns are assigned their text, which MariaDB stores and MySQL parses.
SET @paint := (SELECT `id` FROM `categories` WHERE `slug` = 'paint');
--> statement-breakpoint
SET @store := (SELECT `id` FROM `stores` WHERE `name_ka` = 'ქართული ავეჯი' ORDER BY `id` LIMIT 1);
--> statement-breakpoint
INSERT INTO `products` (`category_id`, `store_id`, `name_ka`, `name_en`, `name_ru`, `slug`, `sku`, `price_per_unit`, `unit`, `coverage_per_unit`, `brand`, `image_url`, `specs`, `tags`, `style_tags`, `texture_url`, `color_hex`, `is_active`, `is_featured`, `sort_order`) SELECT @paint, @store, 'ინტერიერის საღებავი, მქრქალი — თეთრი', 'Interior paint, matt — white', 'Интерьерная краска, матовая — белая', 'paint-interior-white', 'TX-PAINT-INTERIOR-WHITE', '21.0', 'liter', '8.0', NULL, '/uploads/products/tex-paint-interior-white.webp', '{"wet": false, "colors": ["#F1F0EC"], "source": "tint", "license": "CC0", "surfaces": ["wall"], "normalUrl": "/textures/acg-Plaster002-normal.webp", "roughnessUrl": "/textures/acg-Plaster002-rough.webp", "textureScaleM": 2}', '["modern", "scandinavian", "industrial", "vintage", "wall"]', '["modern", "scandinavian", "industrial", "vintage"]', '/textures/paint-white-diffuse.webp', '#F1F0EB', 1, 0, 0 FROM DUAL WHERE @paint IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `products` WHERE `slug` = 'paint-interior-white');
--> statement-breakpoint
INSERT INTO `products` (`category_id`, `store_id`, `name_ka`, `name_en`, `name_ru`, `slug`, `sku`, `price_per_unit`, `unit`, `coverage_per_unit`, `brand`, `image_url`, `specs`, `tags`, `style_tags`, `texture_url`, `color_hex`, `is_active`, `is_featured`, `sort_order`) SELECT @paint, @store, 'ინტერიერის საღებავი, მქრქალი — თბილი თეთრი', 'Interior paint, matt — warm white', 'Интерьерная краска, матовая — тёплая белая', 'paint-interior-warm-white', 'TX-PAINT-INTERIOR-WARM-WHITE', '21.0', 'liter', '8.0', NULL, '/uploads/products/tex-paint-interior-warm-white.webp', '{"wet": false, "colors": ["#F0E9DE"], "source": "tint", "license": "CC0", "surfaces": ["wall"], "normalUrl": "/textures/acg-Plaster002-normal.webp", "roughnessUrl": "/textures/acg-Plaster002-rough.webp", "textureScaleM": 2}', '["scandinavian", "vintage", "modern", "wall"]', '["scandinavian", "vintage", "modern"]', '/textures/paint-warm-white-diffuse.webp', '#F0E9DD', 1, 0, 0 FROM DUAL WHERE @paint IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `products` WHERE `slug` = 'paint-interior-warm-white');
--> statement-breakpoint
INSERT INTO `products` (`category_id`, `store_id`, `name_ka`, `name_en`, `name_ru`, `slug`, `sku`, `price_per_unit`, `unit`, `coverage_per_unit`, `brand`, `image_url`, `specs`, `tags`, `style_tags`, `texture_url`, `color_hex`, `is_active`, `is_featured`, `sort_order`) SELECT @paint, @store, 'ინტერიერის საღებავი, მქრქალი — ნაცრისფერ-ბეჟი', 'Interior paint, matt — greige', 'Интерьерная краска, матовая — серо-бежевая', 'paint-interior-greige', 'TX-PAINT-INTERIOR-GREIGE', '21.0', 'liter', '8.0', NULL, '/uploads/products/tex-paint-interior-greige.webp', '{"wet": false, "colors": ["#D5CEC3"], "source": "tint", "license": "CC0", "surfaces": ["wall"], "normalUrl": "/textures/acg-Plaster002-normal.webp", "roughnessUrl": "/textures/acg-Plaster002-rough.webp", "textureScaleM": 2}', '["modern", "scandinavian", "wall"]', '["modern", "scandinavian"]', '/textures/paint-greige-diffuse.webp', '#D5CEC3', 1, 0, 0 FROM DUAL WHERE @paint IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `products` WHERE `slug` = 'paint-interior-greige');
--> statement-breakpoint
INSERT INTO `products` (`category_id`, `store_id`, `name_ka`, `name_en`, `name_ru`, `slug`, `sku`, `price_per_unit`, `unit`, `coverage_per_unit`, `brand`, `image_url`, `specs`, `tags`, `style_tags`, `texture_url`, `color_hex`, `is_active`, `is_featured`, `sort_order`) SELECT @paint, @store, 'ინტერიერის საღებავი, მქრქალი — ღია ნაცრისფერი', 'Interior paint, matt — light grey', 'Интерьерная краска, матовая — светло-серая', 'paint-interior-light-grey', 'TX-PAINT-INTERIOR-LIGHT-GREY', '21.0', 'liter', '8.0', NULL, '/uploads/products/tex-paint-interior-light-grey.webp', '{"wet": false, "colors": ["#D2D5D4"], "source": "tint", "license": "CC0", "surfaces": ["wall"], "normalUrl": "/textures/acg-Plaster002-normal.webp", "roughnessUrl": "/textures/acg-Plaster002-rough.webp", "textureScaleM": 2}', '["modern", "industrial", "scandinavian", "wall"]', '["modern", "industrial", "scandinavian"]', '/textures/paint-light-grey-diffuse.webp', '#D2D5D5', 1, 0, 0 FROM DUAL WHERE @paint IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `products` WHERE `slug` = 'paint-interior-light-grey');
--> statement-breakpoint
INSERT INTO `products` (`category_id`, `store_id`, `name_ka`, `name_en`, `name_ru`, `slug`, `sku`, `price_per_unit`, `unit`, `coverage_per_unit`, `brand`, `image_url`, `specs`, `tags`, `style_tags`, `texture_url`, `color_hex`, `is_active`, `is_featured`, `sort_order`) SELECT @paint, @store, 'ინტერიერის საღებავი, მქრქალი — თბილი ნაცრისფერი', 'Interior paint, matt — warm grey', 'Интерьерная краска, матовая — тёплая серая', 'paint-interior-warm-grey', 'TX-PAINT-INTERIOR-WARM-GREY', '21.0', 'liter', '8.0', NULL, '/uploads/products/tex-paint-interior-warm-grey.webp', '{"wet": false, "colors": ["#B8B2A9"], "source": "tint", "license": "CC0", "surfaces": ["wall"], "normalUrl": "/textures/acg-Plaster002-normal.webp", "roughnessUrl": "/textures/acg-Plaster002-rough.webp", "textureScaleM": 2}', '["industrial", "modern", "wall"]', '["industrial", "modern"]', '/textures/paint-warm-grey-diffuse.webp', '#B8B2A8', 1, 0, 0 FROM DUAL WHERE @paint IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `products` WHERE `slug` = 'paint-interior-warm-grey');
--> statement-breakpoint
INSERT INTO `products` (`category_id`, `store_id`, `name_ka`, `name_en`, `name_ru`, `slug`, `sku`, `price_per_unit`, `unit`, `coverage_per_unit`, `brand`, `image_url`, `specs`, `tags`, `style_tags`, `texture_url`, `color_hex`, `is_active`, `is_featured`, `sort_order`) SELECT @paint, @store, 'ინტერიერის საღებავი, მქრქალი — ფიქლისფერი', 'Interior paint, matt — slate grey', 'Интерьерная краска, матовая — сланцево-серая', 'paint-interior-slate', 'TX-PAINT-INTERIOR-SLATE', '21.0', 'liter', '8.0', NULL, '/uploads/products/tex-paint-interior-slate.webp', '{"wet": false, "colors": ["#8B9093"], "source": "tint", "license": "CC0", "surfaces": ["wall"], "normalUrl": "/textures/acg-Plaster002-normal.webp", "roughnessUrl": "/textures/acg-Plaster002-rough.webp", "textureScaleM": 2}', '["industrial", "modern", "wall"]', '["industrial", "modern"]', '/textures/paint-slate-diffuse.webp', '#8B9094', 1, 0, 0 FROM DUAL WHERE @paint IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `products` WHERE `slug` = 'paint-interior-slate');
--> statement-breakpoint
INSERT INTO `products` (`category_id`, `store_id`, `name_ka`, `name_en`, `name_ru`, `slug`, `sku`, `price_per_unit`, `unit`, `coverage_per_unit`, `brand`, `image_url`, `specs`, `tags`, `style_tags`, `texture_url`, `color_hex`, `is_active`, `is_featured`, `sort_order`) SELECT @paint, @store, 'ინტერიერის საღებავი, მქრქალი — მოყავისფრო-ნაცრისფერი', 'Interior paint, matt — taupe', 'Интерьерная краска, матовая — серо-коричневая', 'paint-interior-taupe', 'TX-PAINT-INTERIOR-TAUPE', '21.0', 'liter', '8.0', NULL, '/uploads/products/tex-paint-interior-taupe.webp', '{"wet": false, "colors": ["#C3B6A8"], "source": "tint", "license": "CC0", "surfaces": ["wall"], "normalUrl": "/textures/acg-Plaster002-normal.webp", "roughnessUrl": "/textures/acg-Plaster002-rough.webp", "textureScaleM": 2}', '["modern", "vintage", "wall"]', '["modern", "vintage"]', '/textures/paint-taupe-diffuse.webp', '#C3B6A7', 1, 0, 0 FROM DUAL WHERE @paint IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `products` WHERE `slug` = 'paint-interior-taupe');
--> statement-breakpoint
INSERT INTO `products` (`category_id`, `store_id`, `name_ka`, `name_en`, `name_ru`, `slug`, `sku`, `price_per_unit`, `unit`, `coverage_per_unit`, `brand`, `image_url`, `specs`, `tags`, `style_tags`, `texture_url`, `color_hex`, `is_active`, `is_featured`, `sort_order`) SELECT @paint, @store, 'ინტერიერის საღებავი, მქრქალი — სალბისფერი', 'Interior paint, matt — sage', 'Интерьерная краска, матовая — шалфейная', 'paint-interior-sage', 'TX-PAINT-INTERIOR-SAGE', '21.0', 'liter', '8.0', NULL, '/uploads/products/tex-paint-interior-sage.webp', '{"wet": false, "colors": ["#C2CCB9"], "source": "tint", "license": "CC0", "surfaces": ["wall"], "normalUrl": "/textures/acg-Plaster002-normal.webp", "roughnessUrl": "/textures/acg-Plaster002-rough.webp", "textureScaleM": 2}', '["scandinavian", "vintage", "wall"]', '["scandinavian", "vintage"]', '/textures/paint-sage-diffuse.webp', '#C2CCB9', 1, 0, 0 FROM DUAL WHERE @paint IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `products` WHERE `slug` = 'paint-interior-sage');
--> statement-breakpoint
INSERT INTO `products` (`category_id`, `store_id`, `name_ka`, `name_en`, `name_ru`, `slug`, `sku`, `price_per_unit`, `unit`, `coverage_per_unit`, `brand`, `image_url`, `specs`, `tags`, `style_tags`, `texture_url`, `color_hex`, `is_active`, `is_featured`, `sort_order`) SELECT @paint, @store, 'ინტერიერის საღებავი, მქრქალი — მკრთალი ცისფერი', 'Interior paint, matt — dusty blue', 'Интерьерная краска, матовая — пыльно-голубая', 'paint-interior-dusty-blue', 'TX-PAINT-INTERIOR-DUSTY-BLUE', '21.0', 'liter', '8.0', NULL, '/uploads/products/tex-paint-interior-dusty-blue.webp', '{"wet": false, "colors": ["#BCC8CF"], "source": "tint", "license": "CC0", "surfaces": ["wall"], "normalUrl": "/textures/acg-Plaster002-normal.webp", "roughnessUrl": "/textures/acg-Plaster002-rough.webp", "textureScaleM": 2}', '["scandinavian", "modern", "wall"]', '["scandinavian", "modern"]', '/textures/paint-dusty-blue-diffuse.webp', '#BCC8CF', 1, 0, 0 FROM DUAL WHERE @paint IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `products` WHERE `slug` = 'paint-interior-dusty-blue');
--> statement-breakpoint
INSERT INTO `products` (`category_id`, `store_id`, `name_ka`, `name_en`, `name_ru`, `slug`, `sku`, `price_per_unit`, `unit`, `coverage_per_unit`, `brand`, `image_url`, `specs`, `tags`, `style_tags`, `texture_url`, `color_hex`, `is_active`, `is_featured`, `sort_order`) SELECT @paint, @store, 'ინტერიერის საღებავი, მქრქალი — მკრთალი ვარდისფერი', 'Interior paint, matt — dusty rose', 'Интерьерная краска, матовая — пыльно-розовая', 'paint-interior-dusty-rose', 'TX-PAINT-INTERIOR-DUSTY-ROSE', '21.0', 'liter', '8.0', NULL, '/uploads/products/tex-paint-interior-dusty-rose.webp', '{"wet": false, "colors": ["#D7BCB1"], "source": "tint", "license": "CC0", "surfaces": ["wall"], "normalUrl": "/textures/acg-Plaster002-normal.webp", "roughnessUrl": "/textures/acg-Plaster002-rough.webp", "textureScaleM": 2}', '["vintage", "scandinavian", "wall"]', '["vintage", "scandinavian"]', '/textures/paint-dusty-rose-diffuse.webp', '#D7BCB1', 1, 0, 0 FROM DUAL WHERE @paint IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `products` WHERE `slug` = 'paint-interior-dusty-rose');
--> statement-breakpoint
INSERT INTO `products` (`category_id`, `store_id`, `name_ka`, `name_en`, `name_ru`, `slug`, `sku`, `price_per_unit`, `unit`, `coverage_per_unit`, `brand`, `image_url`, `specs`, `tags`, `style_tags`, `texture_url`, `color_hex`, `is_active`, `is_featured`, `sort_order`) SELECT @paint, @store, 'ინტერიერის საღებავი, მქრქალი — კრემისფერი', 'Interior paint, matt — cream', 'Интерьерная краска, матовая — кремовая', 'paint-interior-cream', 'TX-PAINT-INTERIOR-CREAM', '21.0', 'liter', '8.0', NULL, '/uploads/products/tex-paint-interior-cream.webp', '{"wet": false, "colors": ["#EBE2C8"], "source": "tint", "license": "CC0", "surfaces": ["wall"], "normalUrl": "/textures/acg-Plaster002-normal.webp", "roughnessUrl": "/textures/acg-Plaster002-rough.webp", "textureScaleM": 2}', '["vintage", "scandinavian", "wall"]', '["vintage", "scandinavian"]', '/textures/paint-cream-diffuse.webp', '#ECE1C8', 1, 0, 0 FROM DUAL WHERE @paint IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `products` WHERE `slug` = 'paint-interior-cream');
--> statement-breakpoint
INSERT INTO `products` (`category_id`, `store_id`, `name_ka`, `name_en`, `name_ru`, `slug`, `sku`, `price_per_unit`, `unit`, `coverage_per_unit`, `brand`, `image_url`, `specs`, `tags`, `style_tags`, `texture_url`, `color_hex`, `is_active`, `is_featured`, `sort_order`) SELECT @paint, @store, 'ინტერიერის საღებავი, მქრქალი — ზეთისხილისფერი', 'Interior paint, matt — olive', 'Интерьерная краска, матовая — оливковая', 'paint-interior-olive', 'TX-PAINT-INTERIOR-OLIVE', '21.0', 'liter', '8.0', NULL, '/uploads/products/tex-paint-interior-olive.webp', '{"wet": false, "colors": ["#969E86"], "source": "tint", "license": "CC0", "surfaces": ["wall"], "normalUrl": "/textures/acg-Plaster002-normal.webp", "roughnessUrl": "/textures/acg-Plaster002-rough.webp", "textureScaleM": 2}', '["vintage", "industrial", "wall"]', '["vintage", "industrial"]', '/textures/paint-olive-diffuse.webp', '#959E86', 1, 0, 0 FROM DUAL WHERE @paint IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `products` WHERE `slug` = 'paint-interior-olive');
